JuliaData/Parsers.jl

src/tries.jl
Fixed world age issue when starting julia with `--compiled-modules=no`. Fixes https://github.com/JuliaData/CSV.jl/issues/309
Note: I only moved the declaration of `generatebranch(es)` before the `quote` but Github Files changed view is showing it all messy
=> Moved match! function definition to the bottom 

src/strings.jl
We cannot rely on hashes being equal to conclude that strings are equal since hash collisions can happen.
I considered using `x[1] == pointer(y) && x[2] == sizeof(y) && return true` at the top of the function as in Base, to take fast path when strings point to the same memory, but I guess in practice it will almost never happen that an existing string points inside a buffer, right?
=> Fix isequal(x::Tuple{Ptr{UInt8}, Int}, y::String)

src/floats.jl
Leads to this improvement in compile times:
```julia
julia> @time Parsers.parse(Float64, "1.0")
2.006939 seconds (11.01 M allocations: 387.387 MiB, 12.40% gc time)
1.0
julia> @time Parsers.parse(Float64, "1.0")
0.410220 seconds (1.43 M allocations: 67.567 MiB, 6.65% gc time)
1.0
```
=> Add a noinline version of typeparser for floats, so the widened cases don't fully inline

README.md
This updates the README to reflect the changes made in #21
=> Make the type the first argument for parse() in README

src/ints.jl, test/runtests.jl
Fixes #44.
Method `Parsers.typeparser(Int64,...)` did not take into account, that the sign has already been
included in the resulting `x` in line `ints.jl:48`.
=> fix Int64 parse error in case close to overflow (#44)

src/Parsers.jl, src/bools.jl, src/dates.jl, src/floats.jl, src/ints.jl, src/strings.jl, test/runtests.jl
This is basically a bunch of "parsing" functionality that CSV.jl
implemented/needed that should really live here instead. Here's a recap:
* `ignoreemptylines`: this allows skipping empty lines, this is done
when a newline is encountered, we immediately check if another line is
next and if so, consume it, and it will consume as many empty lines as
it encounters
* `comment`: this allows skipping "commented" lines that start with a
certain string; this check is also done after newlines are encountered,
hence internally, this is implemented as `checkcmtemptylines` where both
empty lines and commented lines are checked for simultaneously
* `ignorerepeated`: there was some missing functionality here in that
repeated delimiters that occurred _after_ a newline character weren't
consumed; this …
=> [BREAKING] Implement ignoreemptylines, commented line skipping, and ignorerepeated improvements

src/floats.jl, test/floats.jl
When encountering a decimal character and then immediately an EOF, we
were missing a check that we actually parsed any other digits and just
assumed parsing succeeded; this led to parsing "." as `0.0`. This PR
adds a check that if we saw decimal char and then EOF, if the decimal
char was the only byte consumed, then the value is invalid.
cc: @andreasnoack
=> Don't treat "." as valid float

src/dates.jl, test/dates.jl
This came up in a CSV.jl issue:
https://github.com/JuliaData/CSV.jl/issues/86#issuecomment-624022339,
where an error was being thrown while parsing due to an invalid date.
This breaks the error flow of CSV & Parsers which have their own
error handling stack and signal and handle invalid values without
throwing errors. In the automatic inference case of CSV.jl (where it
decides the types of columns itself while parsing), this should simply
promote the column to a String type. In Parsers with `Parsers.parse`, trying to parse an
invalid date should follow the same pattern as other types and throw a
`Parsers.Error` with the appropriate error codes set on the return code
instead of allowing the Dates module to throw its own error.
=> Ensure invalid dates follow Parsers error flow

src/floats.jl, test/floats.jl
Originally posted as a security issue here:
https://github.com/quinnj/JSON3.jl/issues/57. The problem was that no
matter how many digits were in the input string, we tried to consume
them all, even though there are limits to the number of digits that can
realistically be useful for a given float precision. The change here
checks for those limits and if we go beyond the allowed # of digits,
we'll mark the input as invalid and bail; thus avoiding the "hang"
encountered in the original issue.
=> Don't parse more digits that we know we'll need

src/floats.jl, test/floats.jl
Fixes #53. The issue here is for a single decimal point that was
followed by a delimiter, we weren't hitting the normal code paths like
EOF that marked this invalid. We use the `ndigits` variable that tracks
how many digits we've parsed to check to ensure we've parsed _some_
digits before marking INVALID.
=> Fix successful parsing of single decimal point as valid float

src/Parsers.jl, test/runtests.jl
There were cases like `"10a"` where `Parsers.parse` would consume the
`10` and then stop parsing because it encountered `a` and return
successful. We now have a check for non-IO arguments that we consumed
the full input. For IO, we keep the same behavior where digits will be
consumed and we'll stop once we encountered non-digit. Fixes #55.
=> Make sure Parsers.parse consume full input for non-IO arguments

src/Parsers.jl, src/floats.jl
Also provide an xparse fallback that calls Base.parse on a string.
=> Restrict main parsing to known supported types

.travis.yml, src/Parsers.jl, src/floats.jl, test/floats.jl
This came up in https://github.com/JuliaData/CSV.jl/issues/672, where it was noticed
that CSV.jl was noticeably slower than an alternative parser written in C. After digging
around a bit, I noticed they had a very streamlined float parsing routine, even to the
point of probably being inaccurate (I didn't verify, but based on my knowledge of several
float parsing algorithm implementations, it seems you need a bit more to cover weird
corner cases).
In any case, it made me start looking into Parsers.parse float parsing algorithm and
I noticed there are a good chunk of cases where we hit the slow path for "full" floats,
that have more than 16 digits precision. After doing some more research, I remembered
hearing about Daniel Lemire's recent post about speeding up double parsing for their …
=> Add a 2nd tier of fastpath for float scale

src/floats.jl, test/floats.jl
Fixes JuliaData/CSV.jl#710.
The issue here is that we weren't accounting for exp adjustments when
considering various boundaries. That is, the negative exp boundary was
325, but because you could have a number like 4.94e-324, the exp
actually gets adjusted to 326 (because of the 2 digits after the decimal
place), and we can still accurately calculate this number, but our
boundary was set at 325. This PR adjusts the boundaries to account for
these adjustments and allows sucessfully parsing some of the smallest
allowed floats.
=> Fix edge cases of floats on various type promotion boundaries

src/floats.jl, test/floats.jl
Follow up to https://github.com/JuliaData/Parsers.jl/pull/61, which
didn't quite fix the same issue for non-negative cases.
=> Fix the non-negative case of previous corner case

src/Parsers.jl, src/strings.jl, test/runtests.jl
Fixes #65. The Parsers.parse fallback relied on zero(T) being defined
for the type T we were trying to parse, so we add two separate methods
for Char/Symbol that do what we want instead. This allows CSV.jl to
handle Char/Symbol columns as custom types.
=> Support Char/Symbol parsing from string

src/Parsers.jl, src/precompile.jl
This takes
```jl
@time begin
using Parsers
Parsers.parse(Int, "101")
Parsers.parse(Float64, "101.101")
Parsers.parse(Date, "2018-01-01")
end
``` 
from about 1.4 seconds to 0.5 seconds on julia master.
=> add a few precompile statements

src/floats.jl, test/floats.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/769. The issue here is
our `digits` variable for tracking all digits we've parsed in decimal
form is an unsigned integer, but might be converted to a signed integer
in cases where there's no decimal point or a decimal point with no
trailing digits. It turns out, we don't even need to convert to signed
integer, so the fix is pretty simple of just removing that conversion.
=> Fix signed integer overflow case for float parsing

src/Parsers.jl, test/runtests.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/780. The issue here is
Parsers.Options was assuming ownership of and modifying the input
`sentinel` if it was a `Vector{String}`. The fix is to make a copy
instead and then we can modify and use it to store references to other
strings as needed.
=> Make a copy of input sentinels if provided

src/Parsers.jl, src/floats.jl
Improves timings reported in #70 by about 20x. Most of the performance
improvements come from avoiding BigInt/BigFloat allocations and re-using
thread-local objects for doing the necessary computations. The other
improvements come from avoiding duplicate work; previously, if we were
going to overflow our `digits` variable, which tracks the parsed
mantissa, we basically widened the type and started parsing over again.
In this PR, we restructure the code to allow immediately widening to a
wider typed value and then continuing the parsing algorithm. I think it
reads about as simply as before, so I'm content with that change.
I don't love how messy the `scale` code has gotten; it seems like we
have some duplicated logic between the `UInt128`/`BigInt` mantissa case
and the `UInt64` case, and …
=> Improve float parsing performance for many digits (bigfloat size)

src/strings.jl, test/runtests.jl
Reported by Nils Gudat on slack. The problem here is that we defined our
`sentinelpos` variable at the top of the String parsing method, but
didn't defint `sentstart` until later, since by definition that variable
tracks where the sentinel starts, which might be after an opening quote
character. If we happened to start parsing and reach EOF, with a
provided sentinel string, we then checked at the end of the routine if
`sentstart == pos` and got an undefined variable error. The fix is
pretty easy, just define `sentstart` to be 0 at the top of the routine
along with `sentinelpos` to ensure it's always defined.
=> Fix undefined variable error when sentinel is provided but we reach EOF

src/dates.jl, test/dates.jl
Fixes #60. This is an annoying bug because the stdlib Dates parsing
machinery is all String-based, and the Parsers Dates parsing machinery
is all AbstractVector{UInt8}-based, which left IO out to dry. And
unfortunately, too annoying to write at the most performance low-level.
So we take the easier, but at least correct way out. We parse the date
string as a String, then pass the parsed string to the bytes-based
parsing machinery. So def a little slower than if you're parsing
directly from a string or byte vector, but not crazy bad.
=> Fix timetype parsing on IO sources

src/Parsers.jl, src/utils.jl, test/runtests.jl
Fixed #35. Pretty simple/straightforward. If you want the actual parsed
string, then pass your source + vpos + vlen to `Parsers.getstring` to
get the parsed string out. `vpos` and `vlen` are two of the return
values from `Parsers.xparse` which represent the starting byte position
of the value (`vpos`) and the length in bytes of the parsed string
(`vlen`).
=> Provide getstring utility function for getting parsed string

src/floats.jl, test/floats.jl
Discovered while porting JSON.jl to Parsers 2.0. Unfortunately, the byte
peeking was under an `@inbounds`, so this usually wouldn't error unless
julia was run with `--check-bounds=yes` (which is the default when
running tests thankfully). Good candidate to backport for another 1.X
release.
=> Fix case when float parsing, we failed to check eof before peeking

src/Parsers.jl, test/runtests.jl
Should fix https://github.com/JuliaData/CSV.jl/issues/860. (probably
should backport this to 1.X branch).
=> Fix case where fallback Base.parse throws error

src/floats.jl, test/floats.jl
The issue here is that in the `_scale` method where `v::UInt128`, `v`
might be so large as to lose precision when doing the `x = v /
exp10(-exp)` operation since `exp10(-exp)` will be a `Float64` and hence
our `v` will be promoted to `Float64` before dividing. That's fine if `v
< maxsig(T)`, like in the original `scale` method, but otherwise, we
need to widen `v` and do the division via `BigInt`.
=> Ensure high-precision floats don't default to Float64 for scaling

src/floats.jl, test/floats.jl
Just one extra commit on top of @KristofferC's fix from #100 that refactors a tad so that we avoid making an extra BigFloat copy when parsing negative BigFloats.
I also studied all other return paths from `scale` and `_scale` to ensure the same issue can't be reached in any other way. As a mental note, we could probably speed up BigFloat parsing a bit, or at least avoid a few extra allocations, by either optimizing the fast-path for BigFloats, or just _avoiding_ the fast-path and letting them falldown to the already BigFloat-optimized code. As-is, we do the operation like `x = T(v) * pow10(T, exp)`, which allocates at least 2-3 BigFloats whereas we should be able to only do a single allocation.
=> Fix bug when parsing consecutive, same-thread, non-negative, non-fast-path BigFloats

src/floats.jl, test/floats.jl
Fixes issue reported on slack. The problem is that we have a code path
in `parsedigits` that exits early if we hit EOF and just converts the
integer string to the desired float type. But if there's a dangling
non-digit, like "123A", then we parse the "123" but then there may be
scientific notation or a decimal point, so we pass the parsing off to
the `parsefrac` function which handles both those cases. `parsefrac`
however, doesn't have the convert-integer-to-float return option, so we
pass the parsed digits and, in this case non-existent, `exp` number to
`scale` to "scale" the digits appropriately for the float case. `scale`
can normally handle an `exp` of `0`, _except_ in the case where the
`digits` are bigger than the `maxsig` allowed for `Float64`, in which
case it's converted to a …
=> Fix case where we have a dangling non-digit after integer in float parse

src/Parsers.jl, src/strings.jl, test/runtests.jl
Sorry if this is commandeering your PR @tp2750, but I figured I'd "top it off" for you if that's ok. I used/included your 1st commit in this PR, but did my own implementation in the strings.jl file for how the actual whitespace stripping happens. We needed to ensure it was correctly ignored inside quoted string values and if no delimiter was provided, in addition to the code you had which only considered the delimited case. I know the tests can seem a little intimidating, so I went ahead and added a bunch of test cases for the various quoted/delimited/non-delimited cases we want to check.
=> Successor to #104 for string value whitespace stripping

src/strings.jl, test/runtests.jl
Fixes #106. There were a couple of corner cases missed in the initial
stripwhitespace support for strings when quotes are involved. In
particular, if a string is quoted, then we want to remember the last
non-whitespace position _inside_ the quotes and _not_ update the
position outside the quotes. There were also a few invalid cases we
weren't marking correctly if non-whitespace-non-delimiter characters
were encountered in between close quote character and delimiter.
=> Fix corner cases with stripewhitescpace and quoted/delimited strings

src/precompile.jl, test/runtests.jl
This reduces ttfx of CSV.jl by 12 seconds in these benchmarks:
Current timing with main branches of Parsers.jl and CSV.jl:
```julia
julia> @time using CSV
3.086746 seconds (6.63 M allocations: 375.584 MiB, 7.03% gc time, 88.55% compilation time)
julia> const input="""
time,ping,label
1,25.7,x
2,31.8,y
"""
"time,ping,label\n1,25.7,x\n2,31.8,y\n"
julia> io = IOBuffer(input)
IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=34, maxsize=Inf, ptr=1, mark=-1)
julia> @time file = CSV.File(io)
17.450644 seconds (48.24 M allocations: 1.982 GiB, 6.00% gc time, 99.98% compilation time)
2-element CSV.File:
CSV.Row: (time = 1, ping = 25.7, label = "x")
CSV.Row: (time = 2, ping = 31.8, label = "y")
```
With this PR and main of CSV.jl:
```julia
julia> @time using …
```
=> add precompile runs for xparse and xparse2

src/precompile.jl, test/runtests.jl
This reverts the precompilation changes from #108; this has caused weird precompilation issues for CSV.jl, particularly for windows users transitioning from 1.6 -> 1.7. I'm not sure if there's something in Parsers.jl, or CSV.jl, or core Julia that changed or is unsafe or not precompile friendly, but I don't have the time right now to chase down rabbit holes, so better to just remove for now and we can try to add back later.
=> Revert precompilation

src/floats.jl
this `unsafe_trunc` is undefined behavior. In practice, LLVM generates the same assembly, so this won't be a performance regression.
=> remove undefined behavior

src/floats.jl
`BIGFLOATEXP1` and  `BIGEXP10` are inlined and constant propagated everywhere, and this has a large compilation overhead. Just removing all `@inline` on `_scale` methods gets the whole package precompilation down to 8 seconds!!
These benchmarks are using the reverted precompilation PR on main and this branch.
main:
```julia
julia> @time using Parsers
[ Info: Precompiling Parsers [69de0a69-1ddd-5017-9359-2bf0b02dc9f0]
43.211173 seconds (728.55 k allocations: 65.818 MiB, 0.04% gc time, 1.71% compilation time)
```
This branch:
```julia
julia> @time using Parsers
[ Info: Precompiling Parsers [69de0a69-1ddd-5017-9359-2bf0b02dc9f0]
8.454557 seconds (725.85 k allocations: 41.199 MiB, 0.25% gc time, 10.44% compilation time)
```
Should solve #113
=> dont @inline large constants

src/Parsers.jl, src/strings.jl, test/runtests.jl
Fixes #109. As noted in that issue, stripping whitespace *within* quoted
strings, IMO, should be considered a bug, since one of the primary
reasons for quoting strings in various applications is to delineate the
exact characters that make up the string. This PR fixes
`stripwhitespace` to preserve whitepace encountered within strings, and
only strip whitespace for non-quoted strings (leading or trailing) and
leading/trailing around quoted fields.
On the other hand, there are legitimate use-cases for also stripping
whitespace within quoted strings, so we add a new opt-in `stripquoted`
keyword argument that allows the additional precision of also stripping
whitespace inside quotes. Note that passing `stripquoted=true` implies
`stripwhitespace=true`, so it can be considered a "stronger" …
=> Add new stripquoted keyword arg and fix stripwhitespace

src/strings.jl, test/runtests.jl
- closes #115 (see issue for details)
- ...but i'm not sure if hardcoding  `' '` and `'\t'` as whitespace (when in quotes) is a great idea
- we do hardcode `'\n'` and `'\r'` as newline chars, which seems fairly analogous
- but we do  expose `wh1` and `wh2` for whitespace
- an alternative is to expose `qwh1`, `qwh2` keywords for setting "chars to be considered leading/trailing whitespace in quoted strings", but it'd only be used in this one use-case, so i'm inclined to think we can wait til it's requested
=> Always strip quoted `' '` and `'\t'` when `stripquoted=true`

src/floats.jl, test/floats.jl
Fixes https://github.com/JuliaData/CSV.jl/issues/1007. The issue here is there's
actually a git sha "19129370688824811353f0bcee35b917" where the multithreaded
CSV.File case was trying to detect if this value was a float or not. But attempting
to call `Parsers.xparse` threw an error, which shouldn't happen from the Parsers.xparse
code path (it should just return an error code in the parsing result). The problem
was it parsed the very large integer 19129370688824811353, then `f` which it treated
as the exponenent character, then `0` as the exponent. When it went to do the scaling
code, it promoted the integer to `BigInt`, but the `_scale` BigInt path didn't
handle `0` exponent form. This is easily handled before we promote to `BigInt`
since we're really just looking to convert the large …
=> Fix corner case of very large integer parsing that promotes to BigInt

src/utils.jl
this allows tab completion
```julia
julia> p = Parsers.PosLen(1, 1, false, false);
julia> p.<TAB>
escapedvalue  len           missingvalue  pos
```
=> add `propertynames` for `PosLen`

src/utils.jl, test/runtests.jl
Before this PR, this happened:
```jl
julia> source = IOBuffer("\"str1\" \"str2\"");
julia> opt = Parsers.Options(; quoted=true);
julia> res = Parsers.xparse(String, source, 1, 0, opt);
Parsers.Result{PosLen}(5, 7, PosLen(0x0000000000200004))
julia> @test Parsers.getstring(source, res.val, opt.e) == "str1"
Test Passed
julia> res = Parsers.xparse(String, source, 1 + res.tlen, 0, opt)
Parsers.Result{PosLen}(5, 3, PosLen(0x0000000000900001))
julia> @test Parsers.getstring(source, res.val, opt.e) == "str2"
Test Failed at REPL[7]:1
Expression: Parsers.getstring(source, res.val, opt.e) == "str2"
Evaluated: "s" == "str2"
ERROR: There was an error during testing
```
=> ensure that `getstring` resets the position of IO

src/Parsers.jl
Used to look like (broken list):
Now:
=> fix docstring rendering for xparse

src/Parsers.jl, src/floats.jl, src/ints.jl, src/utils.jl, test/floats.jl, test/runtests.jl
Inspired by the `grouping_mark` option from the R package `readr`, this allows skipping certain characters used to format numbers. I avoided the term `thousand_separators` as different locals use these marks differently (e.g., [indian numbering system](https://en.wikipedia.org/wiki/Indian_numbering_system) would format the number 5000000 as `50,00,000`).
=> Introduce `groupmark` number-parsing option

src/utils.jl
I didn't check, but unbound type parameters often cause performance issues, so this may not be merely cosmetic.
FTR, there's a relevant function in Test in stdlib for checking this stuff:
https://docs.julialang.org/en/v1/stdlib/Test/#Test.detect_unbound_args
=> remove unbound type parameters

Project.toml, src/Parsers.jl, src/floats.jl, src/ints.jl, src/strings.jl, test/runtests.jl
Using Aqua, this PR automates checking for method ambiguities, unbound type parameters, undefined exports, and compat bounds being set.
Using JET to make sure `xparse` doesn't have dynamic dispatch or boxed variables in closures. There seem to be code paths leading to dynamic dispatch when parsing `Date` and `Time` types.
=> Use Aqua and JET in tests

src/strings.jl
Alternative fix for the recent break in InlineStrings
=> Avoid hard-coding String type argument for AbstractString

src/components.jl, test/runtests.jl
Implements https://github.com/JuliaData/Parsers.jl/issues/138.
The biggest question I have is whether we should view this as a bugfix or a breaking change in behavior. I think it's arguable either way.
As a note, this doesn't break anything in current CSV.jl code, which is maybe a signal that this change in behavior isn't super common or makes that much of a difference?
cc: @nickrobinson251, @Drvi
=> Treat empty quoted field as not empty sentinel for Strings

src/components.jl
- missing `d` in `findelimiter` -> `finddelimiter`, made searching in the code more difficult
- adding `_` prefix as no need to actually extend the same function as below (i'm not even sure it would?), and to make distinguishing them in stacktraces a little easier
=> Fix typo in `find[d]elimiter`

src/components.jl, test/runtests.jl
This broke the InlineStrings tests. Regardless of greedy or non-greedy, we want to remove the OK code, since that should be mutually exclusive with the SENTINEL code.
=> Remove OK code when sentinel is matched

benchmarks/parsers.jl, src/Parsers.jl, src/components.jl, src/dates.jl, src/strings.jl, src/utils.jl
Mainly just sprinkling around some `@inline` calls. In the `benchmarks/parsers.jl` file, I have some common types where I'm checking performance of Parsers.jl vs. Base and I also checked the current Parsers.jl release vs. #main branch. Performance looks very very close, with only Strings being about 5% slower. I ran out of gas looking to why that may be, but I think that's within the range of acceptability IMO.
=> Bring performance back to pre-refactor levels

Project.toml, src/utils.jl, test/runtests.jl
- close #150 
- confirmed that `OpenML.load(42638)` works when using this branch of Parsers.jl
=> Fix equality definition between byte and Token

.github/workflows/TagBot.yml, src/strings.jl, src/utils.jl, test/runtests.jl
In the switch to making Char non-greedy in the 2.5 release, I failed to account for the fact that the parsed Char may in fact be the delimiter provided, in which case we want to match the delim instead of treating it as a successfully parsed Char (Char is greedy in this way like Strings).
Luckily we can still do this pretty efficiently by checking our parsed Char against the delimiter, if there is one.
=> Ensure Char doesn't match provided delim before marking OK

src/Parsers.jl, test/runtests.jl
This generalizes the compatibility checks between `escapechar`, `openquotechar`, `closequotechar`, `delim` and the sentinel values. We still fail to correctly validate pairs of regular expressions as those would have to be somehow reduced to their minimal canonical form (I'm sure there is a fancy CS name for this).
=> Extend Options' inputs validation

src/Parsers.jl, src/utils.jl, test/runtests.jl
- adds the tests from 117 (#117) now that 127 is merged (#127) and we want to support `String` quotes (i.e. supersedes 117)
- ~`src/` changes here probably need a bit of tidy up, i did the minimal thing to get tests passing, but i think the `_contains` function could do with a clean-up~
- we should probably go through other things that are now genralised to be `MaybeToken` and check all cases are working as expected... in some follow-up PRs
=> Support open and close quotes being `String`

Project.toml, src/Parsers.jl, test/runtests.jl
Quick fix for https://github.com/JuliaData/CSV.jl/issues/1063
This makes `Flags` serializable, which in turns allows serializing `Options` and, downstream, `CSV.File` and such.
=> Make Flags serializable

src/Parsers.jl, src/floats.jl, src/ints.jl, src/utils.jl
This is an inherently type-unstable operation where we don't know exactly what type of thing we're going to parse, _even_ once we get into the `typeparser`, which isn't usually the case.
This is about 2x faster in the top-level case by switching to a functional style where you pass in an "applicator" function that gets applied to whatever objecdt we end up with. If a user calls the new `parsenumber` directly, they can get near-native performance with their own applicator.
Perf examples:
Before
```
julia> @btime Parsers.parse(Number, "9223372036854775808")
294.762 ns (7 allocations: 240 bytes)
9223372036854775808
julia> @btime Parsers.parse(Number, "1.0")
370.350 ns (9 allocations: 208 bytes)
1.0
julia> @btime Parsers.parse(Number, "1")
249.674 ns (4 allocations: 112 bytes)
1
```
This PR: …
=> Improve performance of Parsers.parse(Number, ...)

src/Parsers.jl, src/components.jl, src/strings.jl, src/utils.jl, test/runtests.jl
`PosLen31` uses 31 bits for both `len` and `pos` fields and thus can represent strings that are in <=2GiB buffers and have up to 2GiB bytes in length. Unexported for now.
=> Introduce PosLen31

src/floats.jl, test/runtests.jl
If we encounter a decimal point, ensure we treat the `Number` as float instead of integer. For the case where we were _almost_ overflowing, we eagerly widen, but if we don't actually overflow, we want to "unwiden" back to the next lowest integer type. Also fix a few String parsing cases.
At some point, we'll make parsing from a string more first-class, but for now, it works when calling the Parsers.parsenumber directly.
=> Fix a few corner cases of new Number parsing

Project.toml, src/Parsers.jl, src/hexadecimal.jl, test/hexadecimal.jl, test/runtests.jl
Adapted from https://github.com/Drvi/ChunkedCSV.jl/pull/28 and extended to support `IO` sources.
=> Introduce SHA1 and UUID type parsers

src/hexadecimal.jl, test/hexadecimal.jl
We were checking `pos <= len` at the wrong place for `UUID`s which have an insufficient length which lead to a bounds error when we were trying to skip over the malformed bytes. In tests we now also actually shrink the `source`, not just the `len` argument, which covers this error.
Fixes #166
=> Fix a error handling in UUID parser

src/Parsers.jl, test/runtests.jl
=> Fixes for `groupmark` validation

src/Parsers.jl, src/floats.jl
This is useful for `FixedDecimal`s, but it would also be useful when parsing `DateTimes` with nanosecond resolution, at least I always had to import them as strings, strip the last couple of digits, and parse again since which is just poor mans rounding. `nothing`, the default value for `rounding`, should mark the value as invalid if it cannot be represented exactly without rounding (do we need `INEXACT` code?)
Best paired with a `Conf`/`TypeParser` approach a la #131 because for some columns rounding might be acceptable but for others, it might not.
=> Introduce `rounding` option

src/floats.jl
A counterpart of `scale` for when there are no fractional digits or exponent.
=> Introduce `noscale`

src/dates.jl
To avoid useless specialization it's better to use `IdDict` for `Type` keys.
I noticed this while debugging some unrelated precompilation issues, but once noticed it seemed worth fixing.
=> Dict{Type,*} -> IdDict{Type,*}

Project.toml, src/Parsers.jl, src/floats.jl, src/ints.jl, test/floats.jl, test/runtests.jl
co-authored with @Drvi 
When parsing unquoted numbers, and `delim` and `groupmark` are set to the same character, what should happen?
e.g. `"1,foo"` or `"1,\"foo\""` or `"1,2.3,foo"` or `"1,2.3,\"foo\""`?
On `main` there is no documented behaviour for this situation.
In practice current behaviour on `main` is:
```julia
julia> for T in (Int, Float64)
println(T)
for c in ("1,foo","1,\"foo\"","1,2.3,foo","1,2.3,\"foo\"")
print(rpad(repr(c), 15), " => ")
println(Parsers.xparse(T, c; delim=',', groupmark=','))
end
end
```
```julia
Int64
"1,foo"         => Parsers.Result{Int64}(code=`INVALID: EOF | INVALID_DELIMITER `, tlen=5, val=1)
"1,\"foo\""     => Parsers.Result{Int64}(code=`INVALID: EOF | INVALID_DELIMITER `, tlen=7, val=1)
"1,2.3,foo"     => Parsers.Result{Int64}(code=`INVALID: OK | …
```
=> When delim=groupmark=`x`, treat `x` as delim unless input is quoted 

.github/workflows/IntegrationTest.yml, Project.toml
- PRs to Parsers.jl will now run the ChunkedCSV.jl tests to ensure there is no accidental breakage to that package
-  e.g. for this PR: https://github.com/JuliaData/Parsers.jl/actions/runs/7021727622/job/19104488100?pr=187
=> Add ChunkedCSV.jl to the integration tests workflow

src/Parsers.jl
Many of these are issues with operations on `Char` rather
than `String`.
=> fix a few lurking bugs detected by JET
